Unified

diff --git a/minon/minion_create b/minon/minion_create
--- a/minon/minion_create
+++ b/minon/minion_create
@@ -6,7 +6,7 @@
 # minion status stored in /var/minion/service
 #minon port X status in /var/minon/ports/X
 
-# Syntax: minion_create -m minion-port-name -i ipsec-adapter-name -a remote-ipsec-address -n ipsec-connection-name -v VXLAN-id
+# Syntax: minion_create -m minion-port-name -i ipsec-adapter-name -a remote-ipsec-address -n ipsec-connection-name -v VXLAN-id -r <hub|spoke> -s <spoke name from Venus, Mars, Earth>
 # Create minion port name PORT with VXlan ID N
 #####
 # Probably need a wrapper for this...
@@ -32,13 +32,16 @@ REMOTE_IPSEC_ADDR=""
 export VAGRANT_ROLE="spoke"
 #export VAGRANT_ROLE="hub"  
 
+export SPOKE_NAME=""
+export HUB_NAME="sun"
+
 #export LOCALIP=192.7.7.4
 export LOCALIP=192.7.7.10
 
 export IPSEC_CONN_NAME=""
 
 # Process options for create operation
-while getopts m:i:a:n:v:r:h option
+while getopts m:i:a:n:v:r:s:h option
 do
    case "${option}" 
    in
@@ -48,7 +51,8 @@ do
    n) IPSEC_CONN_NAME=${OPTARG};;
    v) MPORT_ID=${OPTARG};;
    r) VAGRANT_ROLE=${OPTARG};;
-   h) echo "Syntax: create -m minion-port-name -i ipsec-adapter-name -a remote-ipsec-address -n ipsec-connection-name -v VXLAN-id -r <hub|spoke>"
+   s) SPOKE_NAME=${OPTARG};;
+   h) echo "Syntax: create -m minion-port-name -i ipsec-adapter-name -a remote-ipsec-address -n ipsec-connection-name -v VXLAN-id -r <hub|spoke> -s <spoke name from Venus, Mars, Earth>"
    esac
 done
 if [[ $MPORT == "" ]]; then
@@ -80,6 +84,14 @@ if [[ $VAGRANT_ROLE == "" ]]; then
   echo "Vagrant role (hub or spoke) missing."
   exit 1
 fi
+
+if [[ $VAGRANT_ROLE == "spoke" ]]; then
+	if [[ $SPOKE_NAME = "" ]]; then
+		echo "Spoke name (one of Earth, Mars, or Venus) is missing."
+		exit 1
+	fi
+fi
+
    
 #export MPORT=vxlan0
 #export MPORT_ID=21
@@ -157,7 +169,7 @@ fi
     if [ $VAGRANT_ROLE == "hub" ]
     then
 # %DNSmasq
-       m4 -DMOON_IPADDR="10.210.210.41" /home/vagrant/ipxehttpproxy/strongswan/hosts.m4 > /etc/hosts
+       m4 -DSUN_IPADDR="10.210.210.41" /home/vagrant/ipxehttpproxy/strongswan/hosts.m4 > /etc/hosts
     fi
 
     if [ $VAGRANT_ROLE == "spoke" ]
@@ -204,11 +216,25 @@ fi
 	    nmcli con mod "System eth0" ipv4.ignore-auto-dns yes
 	fi
     fi
+
+
     
     if [ $VAGRANT_ROLE == "spoke" ]
     then
+
 	nmcli con up "System eth0"
-	nmcli general hostname apollo.load ### XYZZY
+	# Select hostname based on spoke name
+	case $SPOKE_NAME in 
+		"Earth" )
+			export SPOKE_HOSTNAME="earth.load" ;;
+		"Venus" )
+			export SPOKE_HOSTNAME="venus.load" ;;
+		"Mars" )
+			export SPOKE_HOSTNAME="mars.load" ;;
+	esac
+
+
+	nmcli general hostname $SPOKE_HOSTNAME
     fi
     
 
@@ -216,7 +242,7 @@ echo "I-PR Prequiresites Verified" > $MINION_STATUS
 
 
 # 2. Check availability of IPsec peer server on network (unencrypted IP address) (I-A)
-ping -c 1 -w 4 moon ### XYZZY
+ping -c 1 -w 4 sun ### XYZZY
 if [[ $? != 0 ]]; then
    echo "IPsec target host unreachable. This is required to establish IPsec tunnel."
 else
@@ -255,16 +281,36 @@ if [ $testswandir != 0 ]; then
 			strongswan pki --gen --outform pem > CAKey.key
 			strongswan pki --self --in CAKey.key --dn "C=US,ST=Indiana,L=West Lafayette,O=Purdue University,emailAddress=tjhacker@purdue.edu,CN=strongSwan CA" --ca --outform pem > CA.crt
 			strongswan pki --gen --outform pem > hostSunKey.key
-			strongswan pki --gen --outform pem > hostMoonKey.key
+			strongswan pki --gen --outform pem > hostVenusKey.key
+			strongswan pki --gen --outform pem > hostMarsKey.key
+			strongswan pki --gen --outform pem > hostEarthKey.key
+####			strongswan pki --gen --outform pem > hostMoonKey.key
 			strongswan pki --issue --in hostSunKey.key --type priv --cacert CA.crt --cakey CAKey.key --dn "C=US,ST=Indiana,L=West Lafayette,O=Purdue University,emailAddress=tjhacker@purdue.edu,CN=sun.localdomain, OU=CIT" --san sun.localdomain --outform pem   > hostSunCert.crt 
-			strongswan pki --issue --in hostMoonKey.key --type priv --cacert CA.crt --cakey CAKey.key --dn "C=US,ST=Indiana,L=West Lafayette,O=Purdue University,emailAddress=tjhacker@purdue.edu,CN=moon.localdomain,OU=CIT" --san moon.localdomain --outform pem    > hostMoonCert.crt 
+			strongswan pki --issue --in hostEarthKey.key --type priv --cacert CA.crt --cakey CAKey.key --dn "C=US,ST=Indiana,L=West Lafayette,O=Purdue University,emailAddress=tjhacker@purdue.edu,CN=earth.localdomain, OU=CIT" --san earth.localdomain --outform pem   > hostEarthCert.crt 
+		strongswan pki --issue --in hostVenusKey.key --type priv --cacert CA.crt --cakey CAKey.key --dn "C=US,ST=Indiana,L=West Lafayette,O=Purdue University,emailAddress=tjhacker@purdue.edu,CN=venus.localdomain, OU=CIT" --san venus.localdomain --outform pem   > hostVenusCert.crt 	
+strongswan pki --issue --in hostMarsKey.key --type priv --cacert CA.crt --cakey CAKey.key --dn "C=US,ST=Indiana,L=West Lafayette,O=Purdue University,emailAddress=tjhacker@purdue.edu,CN=mars.localdomain, OU=CIT" --san mars.localdomain --outform pem   > hostMarsCert.crt 
+####			strongswan pki --issue --in hostMoonKey.key --type priv --cacert CA.crt --cakey CAKey.key --dn "C=US,ST=Indiana,L=West Lafayette,O=Purdue University,emailAddress=tjhacker@purdue.edu,CN=moon.localdomain,OU=CIT" --san moon.localdomain --outform pem    > hostMoonCert.crt 
 		fi
 	 fi
 
         if [ $VAGRANT_ROLE == "spoke" ]
 	then	
+		# Keys to be copied over depends on spoke name
+
+		case $SPOKE_NAME in 
+			"Earth" )
+				export HOST_KEY="hostEarthKey.key" ;;
+			"Venus" )
+				export HOST_KEY="hostVenusKey.key" ;;
+			"Mars" )
+				export HOST_KEY="hostMarsKey.key" ;;
+		esac
+			
 		# Copy over necessary X509 certs using DUO 2FA secure remote copy
-		rsync -e "ssh -p 59842 -o 'UserKnownHostsFile /dev/null' -o 'StrictHostKeyChecking no'" vagrant@moon:/home/vagrant/certs/CA.crt vagrant@moon:/home/vagrant/certs/host*Cert.crt vagrant@moon:/home/vagrant/certs/hostSunKey.key  /home/vagrant/certs
+		rsync -e "ssh -p 59842 -o 'UserKnownHostsFile /dev/null' -o 'StrictHostKeyChecking no'" vagrant@sun:/home/vagrant/certs/CA.crt vagrant@sun:/home/vagrant/certs/host*Cert.crt vagrant@sun:/home/vagrant/certs/$HOST_KEY  /home/vagrant/certs
+###		rsync -e "ssh -p 59842 -o 'UserKnownHostsFile /dev/null' -o 'StrictHostKeyChecking no'" vagrant@moon:/home/vagrant/certs/CA.crt vagrant@moon:/home/vagrant/certs/host*Cert.crt vagrant@moon:/home/vagrant/certs/hostSunKey.key  /home/vagrant/certs
+###		rsync -e "ssh -p 59842 -o 'UserKnownHostsFile /dev/null' -o 'StrictHostKeyChecking no'" vagrant@moon:/home/vagrant/certs/CA.crt vagrant@moon:/home/vagrant/certs/host*Cert.crt vagrant@moon:/home/vagrant/certs/hostVenusKey.key  /home/vagrant/certs
+###		rsync -e "ssh -p 59842 -o 'UserKnownHostsFile /dev/null' -o 'StrictHostKeyChecking no'" vagrant@moon:/home/vagrant/certs/CA.crt vagrant@moon:/home/vagrant/certs/host*Cert.crt vagrant@moon:/home/vagrant/certs/hostMarsKey.key  /home/vagrant/certs
 
   		if [[ $? != 0 ]]; then
 			echo "rsync failed."
@@ -279,20 +325,37 @@ if [ $test_ipsec_conn == 0 ]; then # No active connection - establish ipsec tunn
         if [ $VAGRANT_ROLE == "hub" ]
 	then
            # strongswan configuration file for hub
-             m4 -D__LOCAL_FQDN="moon.localdomain" -D__LOCAL_CERT="hostMoonCert.crt" -D__LOCALIP_TS="192.100.88.0/24" -D__REMOTEIP_TS="192.100.42.0/24" /home/vagrant/ipxehttpproxy/strongswan/uni.conf.m4 > /etc/strongswan/swanctl/conf.d/Olympus.ab.conf
-	    cp /home/vagrant/certs/hostMoonKey.key /etc/strongswan/swanctl/private
+             m4 -D__LOCAL_FQDN="sun.localdomain" -D__LOCAL_CERT="hostSunCert.crt" -D__LOCALIP_TS="192.100.88.0/24" -D__REMOTEIP_TS="192.100.42.0/24,192.100.44.0/24,192.100.46.0/24" /home/vagrant/ipxehttpproxy/strongswan/uni.conf.m4 > /etc/strongswan/swanctl/conf.d/Olympus.ab.conf
+####	    cp /home/vagrant/certs/stSunKey.key /etc/strongswan/swanctl/private
 	fi
 
         if [ $VAGRANT_ROLE == "spoke" ]
 	then
             # strongswan configuration file for spoke
-    	    m4 -D__LOCAL_FQDN="sun.localdomain" -D__REMOTE_FQDN="moon.localdomain" -D__LOCAL_CERT="hostSunCert.crt" -D__REMOTE_CERT="hostMoonCert.crt" -D__LOCALIP_TS="192.100.42.0/24" -D__REMOTEIP_TS="192.100.88.0/24" /home/vagrant/ipxehttpproxy/strongswan/uni.conf.m4 > /etc/strongswan/swanctl/conf.d/ab.conf
-	    cp /home/vagrant/certs/hostSunKey.key /etc/strongswan/swanctl/private
+	    # determine local names based on spoke name
+
+		case $SPOKE_NAME in 
+			"Earth" )
+				export LOCAL_FQDN="earth.localdomain"
+			        export LOCAL_CERT="hostEarthCert.crt"
+			        export LOCAL_TS="192.100.42.0/24" ;;
+			"Venus" )
+				export LOCAL_FQDN="venus.localdomain"
+			        export LOCAL_CERT="hostVenusCert.crt" 
+				export LOCAL_TS="192.100.44.0/24" ;;
+			"Mars" )
+				export LOCAL_FQDN="mars.localdomain"
+			        export LOCAL_CERT="hostMarsCert.crt" 
+				export LOCAL_TS="192.100.46.0/24";;
+		esac
+    	    m4 -D__LOCAL_FQDN=$LOCAL_FQDN -D__REMOTE_FQDN="sun.localdomain" -D__LOCAL_CERT=$LOCAL_CERT -D__REMOTE_CERT="hostSunCert.crt" -D__LOCALIP_TS=$LOCAL_TS -D__REMOTEIP_TS="192.100.88.0/24" /home/vagrant/ipxehttpproxy/strongswan/uni.conf.m4 > /etc/strongswan/swanctl/conf.d/ab.conf
+#####	    cp /home/vagrant/certs/SunKey.key /etc/strongswan/swanctl/private
 	fi
 
 # 3.3 Install certficates for strongswan and start strongswan
      cp /home/vagrant/certs/CA.crt /etc/strongswan/swanctl/x509ca
      cp /home/vagrant/certs/host*Cert.crt /etc/strongswan/swanctl/x509
+     cp /home/vagrant/certs/host*Key.key /etc/strongswan/swanctl/private
 
      systemctl enable strongswan-starter.service
      systemctl start strongswan-starter.service
@@ -411,6 +474,11 @@ echo "V-C VXLan Port Created" > $MINION_STATUS
 		exit 1
 	fi
 
+	# STP must be enabled to prevent loops
+###	ovs-vsctl set bridge ovs-br1 rstp_enable=true
+	# add a flow for the minion port to send out traffic to all ports
+###	ovs-ofctl add-flow ovs-br1 in_port=$MPORT,action=all
+
 ##	ifconfig ovs-br1 $LOCALIP/24
 
 # Use supervisor on hub to keep ethereal test point active
@@ -431,6 +499,13 @@ echo "V-C VXLan Port Created" > $MINION_STATUS
 
         if [ $VAGRANT_ROLE == "spoke" ]
 	then
+		# build and install etherate
+		pushd /usr/local/src
+		git clone https://github.com/jwbensley/Etherate.git
+		cd Etherate
+		./configure.sh
+		make install
+		popd
 		timeout -s INT 120 etherate -i $MPORT -Q 1000 1000 -t 5
 		if [[ $? != 0 ]]; then
 	           echo "Verification of open VXlan connection failed."
@@ -442,14 +517,3 @@ echo "V-Up VXLan Port Up" > $PORT_STATUS
 echo "V-Up VXLan Port Up" > $MINION_STATUS
 
 exit 0
-##systemctl restart squid
-
-
-
-
-
-# Recreate or Create VXlan adapter if it doesn't exist
-
-
-##%	 ip link add vxlan0 type vxlan id 21 dev eth2 dstport 8472
-	 ip link add $MPORT type vxlan id $MPORT_ID dev $IPSEC_ADAPTER dstport 8472
